AFDSearch/AFDSearch/Models/Airport.cs
namespace AFDSearch.Models
{
    public class Airport
    {
        public string Id { get; set; }
        public string Identifier { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Name { get; set; }
        public string Chart { get; set; }
        public string Region { get; set; }
        public string AfdLink { get; set; }
    }
}

AFDSearch/AFDSearch/Models/AirportSearch.cs
using System.Collections.Generic;

namespace AFDSearch.Models
{
    public class AirportSearch
    {
        public AirportSearch()
        {
            AirportSearchResults = new List<Airport>();
        }

        public string SearchText { get; set; }

        public string Filter { get; set; }

        public int Top { get; set; }

        public int Skip { get; set; }

        public long Count { get; set; }

        public List<Airport> AirportSearchResults { get; set; }

        public List<FacetInfo> FacetResults { get; set; }
    }
}

AFDSearch/AFDSearch/Models/FacetInfo.cs
using System.Collections.Generic;

namespace AFDSearch.Models
{
    public class FacetInfo
    {
        public FacetInfo()
        {
            Facets = new Dictionary<string, long>();
        }
        public string FacetName { get; set; }

        public Dictionary<string, long> Facets { get; set; }
    }
}

AFDSearch/AFDSearch/Controllers/AirportController.cs
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AFDSearch.Models;
using BlackBarLabs.Search.Azure;

namespace AFDSearch.Controllers
{
    public class AirportController : Controller
    {
        private const int DefaultTopCount = 500;
        private readonly AzureSearchEngine azureSearchEngine;
        private string indexName;
        private string suggesterName;

        public AirportController()
        {
            indexName = ConfigurationManager.AppSettings["SearchServiceIndexName"];
            suggesterName = ConfigurationManager.AppSettings["SearchServiceSuggesterName"];
            var engines = new SearchEngines("SearchServiceName", "SearchServiceApiKey");
            azureSearchEngine = engines.AzureSearchEngine;
        }
        // GET: Search
        public async Task<ActionResult> Search(AirportSearch model)
        {
            // By default, we want to get back no results, but we want to get facet and count information for the entire result set
            int? top = model.Top == 0 ? DefaultTopCount : model.Top;
            var searchText = model.SearchText;
            if (string.IsNullOrEmpty(searchText) && string.IsNullOrEmpty(model.Filter))
            {
                searchText = "*";
                top = 0;
            }

            // Set up facets
            var facetfields = new List<string>() {"Region", "State", "Chart"};
            var facetResults = new List<FacetInfo>();

            long count = 0;
            var result = await azureSearchEngine.SearchDocumentsAsync<Airport>(indexName, searchText, facetfields, true, top, model.Skip,
                model.Filter, 
                airport => new Airport() {Id = airport.Id, Identifier = airport.Identifier, Name = airport.Name, City = airport.City, State = airport.State, Chart = airport.Chart, Region = airport.Region, AfdLink = airport.AfdLink},
                (facetName, facets) =>
                {
                    facetResults.Add(new FacetInfo() {FacetName = facetName, Facets = facets});
                },
                documentCount => { if (null != documentCount) count = documentCount.Value; });

            var resultsModel = new AirportSearch();
            resultsModel.SearchText = model.SearchText;
            resultsModel.AirportSearchResults = result.ToList();
            resultsModel.FacetResults = facetResults;
            resultsModel.Filter = model.Filter;
            resultsModel.Top = model.Top;
            resultsModel.Skip = model.Skip;
            resultsModel.Count = count;


            return View(resultsModel);
        }
    }
}

AFDSearch/AFDSearch/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AFDSearch.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AFDSearch/AFDSearch/Views/Airport/Search.cshtml
@using AFDSearch.Models
@model AirportSearch
@{
    ViewBag.Title = "Airport Search";
}
@{
    const int pageSize = 10;
    int currentPage = 0;
}
<style>
    p {
        font-size: 12px; 
    }
    ul, li{
        margin-top: -10px;
    }
</style>

<table>
    <tr>
        <td valign="top">
            @using (Html.BeginForm("Search", "Airport", FormMethod.Post))
            {
                <input type="submit" value="Clear" />
            }

            @foreach (FacetInfo facetInfo in Model.FacetResults)
            {
                <p>@facetInfo.FacetName</p>
                <ul>
                    @foreach (var facet in facetInfo.Facets)
                    {
                        var facetText = @facet.Key + "(" + facet.Value + ")";
                        var filter = string.IsNullOrEmpty(@Model.Filter) ? string.Empty : @Model.Filter + " and ";
                        <p style="margin: 0">@Html.ActionLink(facetText, "Search", new AirportSearch() {Top = pageSize, Skip = currentPage * pageSize, Filter = filter + @facetInfo.FacetName + " eq '" + @facet.Key + "'"})</p>
                    }
                </ul>
            }
        </td>

        <td valign="top">

            @using (Html.BeginForm("Search", "Airport", FormMethod.Post))
            {
                @Html.TextBoxFor(m => m.SearchText)

                <input type="submit" value="Search"/>
            }

            <table>
                <tr>
                    <th style="border: 1px solid black; padding: 5px;">Identifier</th>
                    <th style="border: 1px solid black; padding: 5px;">Name</th>
                    <th style="border: 1px solid black; padding: 5px;">City</th>
                    <th style="border: 1px solid black; padding: 5px;">State</th>
                    <th style="border: 1px solid black; padding: 5px;">Chart</th>
                    <th style="border: 1px solid black; padding: 5px;">Region</th>
                    <th style="border: 1px solid black; padding: 5px;">Airport Facilities Directory</th>
                </tr>
                @foreach (Airport airport in Model.AirportSearchResults)
                {
                    <tr>
                        <td style="border: 1px solid black; padding: 5px;">@airport.Identifier</td>
                        <td style="border: 1px solid black; padding: 5px;">@airport.Name</td>
                        <td style="border: 1px solid black; padding: 5px;">@airport.City</td>
                        <td style="border: 1px solid black; padding: 5px;">@airport.State</td>
                        <td style="border: 1px solid black; padding: 5px;">@airport.Chart</td>
                        <td style="border: 1px solid black; padding: 5px;">@airport.Region</td>
                        <td style="border: 1px solid black; padding: 5px;"><a href="@airport.AfdLink">@airport.AfdLink</a></td>
                    </tr>
                }
            </table>

            @{
                var pageInfo = string.Empty;
                if (Model.AirportSearchResults.Count > 0)
                {
                    var first = @Model.Skip + 1;
                    var last = @Model.Skip + pageSize;
                    pageInfo = first + " - " + last + " of " + @Model.Count;
                }

                int prevSkip = @Model.Skip - pageSize;
                int nextSkip = @Model.Skip + pageSize;
            }
            @{
                if (prevSkip < 0)
                {
                    prevSkip = 0;
                }
                if (nextSkip > (int)Model.Count)
                {
                    nextSkip = @Model.Skip;
                }
            }

            @if (Model.AirportSearchResults.Count > 0)
            {
                <p style="margin: 0">
                    @Html.ActionLink("Previous", "Search", new AirportSearch() {Top = pageSize, Skip = prevSkip, Filter = @Model.Filter})
                    @pageInfo
                    @Html.ActionLink("Next", "Search", new AirportSearch() {Top = pageSize, Skip = nextSkip, Filter = @Model.Filter})
                </p>
            }
        </td>
    </tr>
</table>

AFDSearch/AFDSearch/Views/Home/Index.cshtml
@using AFDSearch.Models
@model AirportSearch
@{
    ViewBag.Title = "Airport Search";
}

@using (Html.BeginForm("Search", "Airport", FormMethod.Post))
{
    @Html.TextBoxFor(m => m.SearchText)

    <input type="submit" value="Search" />
}

AFDSearch/AFDSearch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>